### PR TITLE
Fixed null checks in SongView

### LINKED ISSUE #337: Tapping on a playlist crashes the app
Using Airsonic server, latest Ultrasonic from F-Droid.  Tapping on a playlist on the list of playlists causes a crash and a return to the main menu.  Here is the traceback:

```
10-22 16:51:34.519 32216 32216 E AndroidRuntime: FATAL EXCEPTION: main
10-22 16:51:34.519 32216 32216 E AndroidRuntime: Process: org.moire.ultrasonic, PID: 32216
10-22 16:51:34.519 32216 32216 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.setVisibility(int)' on a null object reference
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at org.moire.ultrasonic.view.SongView.setSong(SourceFile:268)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at org.moire.ultrasonic.view.EntryAdapter.getView(SourceFile:111)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2387)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.ListView.makeAndAddView(ListView.java:2067)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.ListView.fillDown(ListView.java:793)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.ListView.fillFromTop(ListView.java:855)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.ListView.layoutChildren(ListView.java:1838)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.AbsListView.onLayout(AbsListView.java:2184)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SourceFile:625)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(SourceFile:530)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at net.simonvt.menudrawer.SlidingDrawer.onLayout(SourceFile:146)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.View.layout(View.java:22844)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3470)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2938)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:731)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:43)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: Error reporting crash
10-22 16:51:34.519 32216 32216 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:540)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:5182)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:158)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at org.moire.ultrasonic.activity.SubsonicTabActivity$SubsonicUncaughtExceptionHandler.uncaughtException(SourceFile:1240)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
10-22 16:51:34.519 32216 32216 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
10-22 16:51:34.519 32216 32216 I Process : Sending signal. PID: 32216 SIG: 9
10-22 16:51:34.552  1377  1637 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
```

### PR DESCRIPTION
**Pull request by nitehu**
Fixes #337 

The problem was that the viewHolder can be either a song_list_item or a video_list_item, and these have different elements. Before setting anything the fields must be checked for null - and a few null checks were missing.
The null coalescing and safe calls are nicer to implement in Kotlin, and this wasn't a complex class, so I've migrated it from java.

### CODE REVIEW

File: ultrasonic/src/main/kotlin/org/moire/ultrasonic/view/SongView.kt [hunk 1]
```diff
@@ -0,0 +1,395 @@
...
+import org.moire.ultrasonic.service.MusicServiceFactory.getMusicService
+import org.moire.ultrasonic.util.Util
+import org.moire.ultrasonic.util.VideoPlayerType
+import org.moire.ultrasonic.view.EntryAdapter.SongViewHolder
+import timber.log.Timber
+
+/**
+ * Used to display songs in a `ListView`.
+ *
+ * @author Sindre Mehus
```
Comment (ogarcia) [inline ultrasonic/src/main/kotlin/org/moire/ultrasonic/view/SongView.kt]: You can remove this, the code is yours and it is not necessary to quote the author of deleted code. If you want you can add your name :wink:

File: ultrasonic/src/main/kotlin/org/moire/ultrasonic/view/SongView.kt [hunk 2]
```diff
@@ -0,0 +1,395 @@
...
+
+ Subsonic is distributed in the hope that it will be useful,
+ but WITHOUT ANY WARRANTY; without even the implied warranty of
+ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ GNU General Public License for more details.
+
+ You should have received a copy of the GNU General Public License
+ along with Subsonic.  If not, see <http://www.gnu.org/licenses/>.
+
+ Copyright 2009 (C) Sindre Mehus
```
Comment (ogarcia) [inline ultrasonic/src/main/kotlin/org/moire/ultrasonic/view/SongView.kt]: As a new file. I think that Copyright must be:
`Copyright 2020 (C) Your name`

File: ultrasonic/src/main/kotlin/org/moire/ultrasonic/view/SongView.kt (hunk 1 above)
Comment (nitehu) [reply ultrasonic/src/main/kotlin/org/moire/ultrasonic/view/SongView.kt]: Oh okay! I've removed the author as I strongly believe creating this code is a team effort.

File: ultrasonic/src/main/kotlin/org/moire/ultrasonic/view/SongView.kt (hunk 2 above)
Comment (nitehu) [reply ultrasonic/src/main/kotlin/org/moire/ultrasonic/view/SongView.kt]: Fixed.

File: ultrasonic/src/main/kotlin/org/moire/ultrasonic/view/SongView.kt (hunk 1 above)
Comment (ogarcia) [reply ultrasonic/src/main/kotlin/org/moire/ultrasonic/view/SongView.kt]: Yes, is a team effort, but in new code cannot put other name as author because is _a lie_. The original authors are always credited in git history and in contributors list.
